[tool.poetry]
name = "fastnode"
version = "0.1.0"
description = "FastNode-Graphics Self-Lerning Engine for Cognitive GUI"
authors = ["Forti Shield <dev.sulaiman@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
kombu = "5.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
